version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dynamicforms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dynamicforms
      DB_USERNAME: postgres
      DB_PASSWORD: password
      JWT_SECRET: ChangeThisSecret233222232343243243243243242432432432432423432432432423ToAStrongOne
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  pgdata: