server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dynamicforms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:ChangeThisSecret233222232343243243243243242432432432432423432432432423ToAStrongOne}
  expirationMs: 3600000 # 1 hour

cors:
  allowed-origins: "http://localhost:3000"

logging:
  level:
    org.springframework.security: INFO